### ISSUE TITLE
Off-by One Coordinates

### ISSUE THREAD

**Issue by nathanhaigh** [elsiklab/multibigwig#15] opened 2017-07-10 13:03 UTC
There appears to be an off-by-one error in the display of `MultiXYPlot` (`MultiXYDensity` is not affected) as shown in the following screenshots. The screenshots have the following tracks:

1. gene feature track showing parts of 2 alternative splice forms
2. read alignments in BAM format
3. BigWig coverage file derived from the above BAM file
4. multi bigwig generated from the above bigwig plus one other
5. juctions file

![image](https://user-images.githubusercontent.com/2037575/28019098-d9e23132-65be-11e7-80d9-e85b92e18b7a.png)

The same off-by-one is observed at the other end of this spliced alignment:

![image](https://user-images.githubusercontent.com/2037575/28019231-5f7000e0-65bf-11e7-99ac-88b29c264f6f.png)

**Comment by cmdcolin** [comment] 2017-07-10 15:07
Looks like that is confirmed, should be fixed now!

**Comment by cmdcolin** [comment] 2017-07-10 15:07
Ref https://github.com/elsiklab/multibigwig/commit/4b37dab2c0575c4ae631da2a6be8aac4a137bb80

**Comment by cmdcolin** [comment] 2017-07-10 15:07
Let me know if that helps

**Comment by nathanhaigh** [comment] 2017-07-10 22:25
That fixed it! Great turn-around!

**Closed** 2017-07-10 22:25 UTC
